export const DUMMY_ENTRIES = [
    {
        comName: "Arya Enterprises",
        comPersonName: "Mr. Ravi Kumar",
        comEmail: "ravikumar@arya.com",
        comMobile: "9876543210",
        comAddress: "1234 MG Road, Bangalore, Karnataka",
    },
    {
        comName: "Shree Ganesh Industries",
        comPersonName: "Ms. Priya Sharma",
        comEmail: "priyasharma@ganesh.com",
        comMobile: "9056123456",
        comAddress: "5678 Kamla Nagar, Delhi",
    },
    {
        comName: "Bharat Steel Works",
        comPersonName: "Mr. Rajesh Patel",
        comEmail: "rajeshpatel@bharatsteel.com",
        comMobile: "8899776655",
        comAddress: "34, Sardar Patel Marg, Ahmedabad, Gujarat",
    },
    {
        comName: "Indo Tech Solutions",
        comPersonName: "Ms. Aarti Mehta",
        comEmail: "aartimehta@indotech.com",
        comMobile: "9988776655",
        comAddress: "22, Vikas Colony, Mumbai, Maharashtra",
    },
    {
        comName: "Saraswati Creations",
        comPersonName: "Mr. Anil Yadav",
        comEmail: "anilyadav@saraswati.com",
        comMobile: "7778889990",
        comAddress: "129, Kacheri Road, Lucknow, Uttar Pradesh",
    },
    {
        comName: "Vishal Exports",
        comPersonName: "Ms. Neha Gupta",
        comEmail: "nehagupta@vishalexports.com",
        comMobile: "8034567890",
        comAddress: "45, Churchgate, Chennai, Tamil Nadu",
    },
    {
        comName: "Laxmi Builders",
        comPersonName: "Mr. Suresh Reddy",
        comEmail: "sureshreddy@laxmibuilders.com",
        comMobile: "9198765432",
        comAddress: "102, Jubilee Hills, Hyderabad, Telangana",
    },
    {
        comName: "Kailash Enterprises",
        comPersonName: "Ms. Seema Verma",
        comEmail: "seemaverma@kailash.com",
        comMobile: "8002345678",
        comAddress: "8, C.R. Park, Kolkata, West Bengal",
    },
    {
        comName: "Radha Krishna Spices",
        comPersonName: "Mr. Deepak Joshi",
        comEmail: "deepakjoshi@radhakrishna.com",
        comMobile: "7771234567",
        comAddress: "24, Rani Bagh, Jaipur, Rajasthan",
    },
    {
        comName: "Sundar & Co.",
        comPersonName: "Ms. Ritu Singh",
        comEmail: "ritusingh@sundarco.com",
        comMobile: "9567891234",
        comAddress: "101, Patiala House, Chandigarh",
    },
];
